food/urls.py
from django.urls import path
from food.views import *
app_name='food'
urlpatterns=[
    path('veg/',veg, name='veg'),
]

movie/urls.py
from django.urls import path
from movie.views import *
app_name='movie'
urlpatterns=[
    path('pushpa/',pushpa,name='pushpa'),
]

specificurlnav/urls.py
from django.contrib import admin
from django.urls import path ,include
import movie,food


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/',include('movie.urls')),
    path('food/',include('food.urls')),
    
]

food/models.py
from django.db import models

# Create your models here.

movie/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.
def veg(request):
    return render(request,'veg.html')

movie/views.py
from django.shortcuts import render

# Create your views here.
def pushpa(request):
    return render(request,'pushpa.html')

templates/pushpa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie</title>
</head>
<body>
    <center>
        <h1>pushpa anta flower anukuntiva fire kadha ,kadhu wildfire</h1>
        <a href="{% url 'food:veg' %}">click here to go to next page</a>
        <img src="https://images.ottplay.com/images/allu-arjun-in-pushpa-2-the-rule-1732981220.jpg">
    </center>
</body>
</html>

templates/veg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food</title>
</head>
<body>
    <center>
        <h1>this is belongs to veg</h1>
        <a href="{% url 'movie:pushpa' %}">click here go to next page</a>

        <img src="https://tse3.mm.bing.net/th?id=OIP.TZTSdAmceXmvPPqo4lAcZwHaE7&pid=Api&P=0&h=180">
    </center>
</body>
</html>